package com.example.parameterization.Enum;

public enum MedicationStrength {

    STRENGTH_1_PERCENT,
    STRENGTH_2_PERCENT,
    STRENGTH_5_PERCENT,
    STRENGTH_10_PERCENT,
    STRENGTH_5MG_PER_ML,
    STRENGTH_10MG_PER_ML,
    STRENGTH_20MG_PER_ML,
    STRENGTH_50MG_PER_ML,
    STRENGTH_100MG_PER_ML,
    STRENGTH_50MG,
    STRENGTH_100MG,
    STRENGTH_250MG,
    STRENGTH_500MG,
    STRENGTH_1000MG
}
